# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170904_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiercomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='hiercomment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名称'),
        ),
    ]
