# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_hiercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiercomments', to='blog.Post', verbose_name='文章'),
        ),
    ]
