# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170822_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiercomment',
            old_name='body',
            new_name='content',
        ),
    ]
